package uz.g4.ecommerce.domain.entity.user;

public enum Permission {
    CREATE_USER, CREATE_PRODUCT, CREATE_CATEGORY,
    GET_USER, GET_ORDER, GET_PRODUCT, GET_CATEGORY,
    DELETE_PRODUCT, EDIT_USER, EDIT_PRODUCT, EDIT_CATEGORY,ADD,EDIT,DELETE,GET

}
